export const GET_TASKS = "GET_TASKS"
export const GET_PRIORITIES = "GET_PRIORITIES"
export const GET_STATUSES = "GET_STATUSES"
export const GET_USERS = "GET_USERS"

export const IS_OPEN_EDIT_MODAL = "MODAL/IS_OPEN_EDIT_MODAL"
export const IS_OPEN_CREATE_MODAL = "MODAL/IS_OPEN_CREATE_MODAL"
export const GET_CURRENT_TASK = "MODAL/GET_CURRENT_TASK"

